### ISSUE TITLE
Error Instagram 

### ISSUE THREAD

**Issue by Dmitri3v** [Deadshot0x7/007-TheBond#30]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/007-TheBond/src/007-TheBond.py", line 130, in <module>
    check(inputt)
  File "/data/data/com.termux/files/home/007-TheBond/src/007-TheBond.py", line 23, in check
    acc = dox(inputt)
          ^^^^^^^^^^^
  File "/data/data/com.termux/files/home/007-TheBond/src/igdox.py", line 10, in __init__
    self.doxed = json.loads(final_process)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Deadshot0x7** [comment]
carefully enter the requirement
