### ISSUE TITLE
Help me please with this error

### ISSUE THREAD

**Issue by tonymaroun** [Deadshot0x7/007-TheBond#35]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/007-TheBond/src/007-TheBond.py", line 2, in <module>
    import pyfiglet
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyfiglet/__init__.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Can u help me?

**Comment by Deadshot0x7** [comment]
use python2.7 and you're good to go

**Comment by tonymaroun** [comment]
So python3 doesn't work?

**Comment by Deadshot0x7** [comment]
Yep , don't worry will  refactor it soon
