### ISSUE TITLE
I can usually figure it out but I'm exhausted by this one..

### ISSUE THREAD

**Issue by CamsShaft** [Deadshot0x7/007-TheBond#41]
I've backtracked so many times and I still have no idea why it doesn't run. I didn't even want to ask for help but I think I've turned my brain into that drug commercial where the guy smashes an egg with a frying pan. Definitely my brain on termux... and probably drugs. Can't wait to feel stupid when it's super easy probably.

~/007-TheBond/src $ python3 007-TheBond.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/007-TheBond/src/007-TheBond.py", line 2, in <module>
    import pyfiglet
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyfiglet/__init__.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by Deadshot0x7** [comment]
```
pip install pkg_resources
````
